bug fixed and version updated
GoogleCloudPlatform/cloud-for-marketing pull request #73
Opened 2024-11-19 09:41 UTC by bugrabuga

2024-11-19 10:33 UTC, bugrabuga commented
Hi,

I don't understand what you mean by changes in formatting, from single quotes to double quotes?
Python 3.8 version does not work on GCP, so I updated Python to the latest version, most of the changes in libraries are related to deprecating the version, while creating the dataflow template, BigQueryWrapper in bq_mod now includes a priority parameter, so it was necessary to add this, we tested the changes and went over them with the Google Turkey team, can you review the changes again?

Thanks again !

2024-11-20 07:38 UTC, bugrabuga commented
I changed the double quotes in the setup file to single quotes and rolled back the python version. Currently there are only version updates and parameter updates. Can you review it again?

2024-11-20 16:05 UTC, mohabfekry requested changes

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +FieldSchema = collections.namedtuple("FieldSchema", "fields mode name type")
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +    return value == "true"
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +    return value.encode("utf-8")
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>          }
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +        value = json.loads(value.decode("utf-8"))
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>              else:
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>          elif table is not None:
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +            )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>      def estimate_size(self):
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>              return int(table.numBytes)
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>              ]
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>      def _setup_temporary_dataset(self, bq):
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +        )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +    @check_accessible(["query"])
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
>          bq.wait_for_bq_job(job_ref)
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +        )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +        cleanup_signal = output["cleanup_signal"]
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +        )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +                )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +        gcs_base = ""
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +            )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +            raise ValueError("Invalid GCS location: {}".format(gcs_location))
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +                )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/bigquery_mod/__init__.py
> +        )
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/install.sh
> +printf "\nEND - FoCVS installation completed successfully!\n"
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/requirements.txt
> +# This file is autogenerated by pip-compile with Python 3.12
regenerate using Python 3.8

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/setup.py
>      ],
please revert

2024-11-20 16:05 UTC, mohabfekry commented on marketing-analytics/predicting/future-customer-value-segments/setup.py
> +    version="1.0.0",
please revert

2024-11-21 09:30 UTC, mohabfekry approved these changes
Thanks for the update!

2024-11-21 09:47 UTC, bugrabuga commented
This is my first contribution to an open-source project, please forgive my question, but do I need to do anything else from now on or will my contribution be published in this project :)

2024-11-21 09:51 UTC, mohabfekry commented
No that's all, your contribution will be merged very soon as we're running some final internal checks. Thank you!

2024-11-21 10:04 UTC, bugrabuga commented
Thank you !

2024-11-21 14:08 UTC, merged